{% set data = load_setup_py_data() %}

package:
  name: cansen
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - cansen = cansen.__main__:main


requirements:
  build:
    - python >=3.4,{{PY_VER}}*

  run:
    - python {{PY_VER}}*
    - numpy >=1.8
    - pytables
    - cantera

test:
  imports:
    - cansen

about:
  home: https://github.com/bryanwweber/CanSen
  license: MIT
  license_file: LICENSE.txt
